services:
  - type: web
    name: meta-ads-dashboard
    runtime: node
    plan: free
    rootDir: dashboard
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: META_ACCESS_TOKEN
        sync: false